AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for two Lambda functions that interact with YouTube, S3, and SQS.

Resources:

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: youtube-video-downloads-20230805

  MySQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: youtube-playlist-queue-20230805

  DownloadYouTubeVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/download_youtube_video.py
      Handler: download_youtube_video.lambda_handler
      Runtime: python3.8
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref MyS3Bucket
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sqs:SendMessage'
              Resource: !GetAtt MySQSQueue.Arn

  SendPlaylistToSQSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/send_playlist_to_sqs.py
      Handler: send_playlist_to_sqs.lambda_handler
      Runtime: python3.8
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sqs:SendMessage'
              Resource: !GetAtt MySQSQueue.Arn

