AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Download youtube video and save to s3

Globals:
  Function:
    Timeout: 300

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
  DLEngine:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          BUCKET_NAME: !Ref S3Bucket
      Policies:
      - S3WritePolicy:
          BucketName: !Ref S3Bucket
      PackageType: Image
      Architectures:
        - x86_64
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: dl_engine/
      DockerTag: dl_engine-v1

Outputs:
  BucketName:
    Description: "BucketName"
    Value: !Ref S3Bucket
